#!/usr/bin/env bash


function title(){
    output=$(playerctl --player=spotify metadata title 2>&1)

    if [[ "$output" != *"No players found"* ]]; then
        echo "$output"
    else
        echo "Nothing playing"
    fi
}  


function artist(){ 
    output=$(playerctl --player=spotify metadata artist 2>&1)

    if [[ "$output" != *"No players found"* ]]; then
        echo "$output"
    else
        echo "Silence" 
    fi
}


function player_icon(){
    status=$(playerctl --player=spotify status)
    
    if [ "$status" = "Playing" ]; then
        echo "󰏤"
    elif [ "$status" = "Paused" ]; then
        echo "󰐊"
    elif [ "$status" = "Stopped" ]; then
        echo "󰐊"
    else
        echo "󰏤" 
    fi
} 



case "$1" in 
    "--artist")
        artist
    ;;

    "--title") 
        title 
    ;; 
    "--icon")
        player_icon
    ;;  
    
    "--pos") 
        printf %.2f$(playerctl position)
    ;; 
    
    *) 
    echo "use --title or --icon"
    ;; 

esac 
